<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>页面首页</title>
<link href="${request.contextPath}/css/bootstrap.min.css" rel="stylesheet" >
<link href="${request.contextPath}/css/main-body.css" rel="stylesheet" >
<link rel="stylesheet" type="text/css" href="${request.contextPath}/css/bootstrap-plugins/bootstrap.textbox.css">
<script type="text/javascript" src="${request.contextPath}/js/jquery-3.5.1.min.js"></script>
</head>
<body>
	我是test了
</body>
</html>
